changelog:
  categories:
    - title: New Features
      labels: [enhancement]
    - title: Bug Fixes
      labels: [bug]
    - title: Refactoring
      labels: [refactor]
    - title: Tests
      labels: [test]
    - title: Documentation
      labels: [documentation]
    - title: Maintenance
      labels: [chore, dependencies, github_actions]
    - title: Other Changes
      labels: ["*"]
